### ISSUE TITLE
SearchDto

### ISSUE THREAD

**Issue by nathanatrhea** [RHEAGROUP/UI-DSM#179]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the UI-DSM
- [x] I have searched [open](https://github.com/RHEAGROUP/UI-DSM/issues) and [closed](https://github.com/RHEAGROUP/UI-DSM/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Add the generated SearchDtos for the UI DSM DataModel
### System Configuration

- UI-DSM version:
  - [ ] UI-DSM:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by antoineatrhea** [comment]
The SearchDTO are the same as the UI-DSM DTO. https://github.com/RHEAGROUP/UI-DSM/pull/223 closed this
