### ISSUE TITLE
Setup CI/CD pipeline

### ISSUE THREAD

**Issue by antoineatrhea** [RHEAGROUP/UI-DSM#4]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the UI-DSM
- [x] I have searched [open](https://github.com/RHEAGROUP/UI-DSM/issues) and [closed](https://github.com/RHEAGROUP/UI-DSM/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Setup CI/CD for this repository

### System Configuration

- UI-DSM version:
  - [ ] UI-DSM:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by samatrhea** [comment]
@antoineatrhea have a look at the reqifviewer and reqifsharp projects for inspiration
