### ISSUE TITLE
AppReviewCard

### ISSUE THREAD

**Issue by antoineatstariongroup** [RHEAGROUP/UI-DSM#89]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of the UI-DSM
- [x] I have searched [open](https://github.com/RHEAGROUP/UI-DSM/issues) and [closed](https://github.com/RHEAGROUP/UI-DSM/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

Create an AppReviewCard that derives from the AppProjectCard. The component should also have a field for the ReviewNumber to have something like #number in grey.

### System Configuration

- UI-DSM version:
  - [ ] UI-DSM:         
  - [ ] Other:              
- Environment (Operating system, version and so on):
- .NET Framework version:
- Additional information:

**Comment by antoineatrhea** [comment]
Already done
